#!/usr/bin/env zsh

function safe_source
{
	[[ -a "$1" ]] && source "$1"
}

function is_installed
{
	command -v "$1" >/dev/null 2>&1
	return "$?"
}

export TERM=${TERM:-xterm-color}
export USER=${USER:-$(id -un)}
export HOME=${HOME:-$(grep $USER /etc/passwd | cut -d : -f 6)}
export HOSTNAME=${HOSTNAME:-$(uname -n)}

export IFS=${IFS:-" \t\n\0"}

export ZSH_ROOT="$HOME/.zsh.d"
export ZSH_CUSTOM="$ZSH_ROOT/custom"
export BOX_RISK_LEVEL=2

eval $(/usr/bin/systemctl --user show-environment)
