#!/usr/bin/env zsh

# TRAMP is really picky so just disable zsh
if [[ "$TERM" == "tramp" ]]; then
	unsetopt zle
	unsetopt prompt_cr
	unsetopt prompt_subst

	if whence -w precmd >/dev/null; then
		unfunction precmd
	fi

	if whence -w preexec >/dev/null; then
		unfunction preexec
	fi
	PS1='$ '

	return
fi

source "${ZSH_HOME}/init.zsh"
